sudo: required
service:
  - docker

before_install:
  - docker build -t kazekagekun/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kazekagekun/docker-react npm run test -- --coverage